"""add photo_url to patients and people

Revision ID: 9ab8be1aaab9
Revises: 4119539e72a8
Create Date: 2026-09-15 12:40:46.870267
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ab8be1aaab9'
down_revision: Union[str, Sequence[str], None] = '4119539e72a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('people', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'photo_url')
    op.drop_column('patient_profiles', 'photo_url')
    # ### end Alembic commands ###
