"""add push token, timezone, security

Revision ID: 7e25e5eb71ef
Revises: 45914451cfe1
Create Date: 2026-09-09 19:56:01.173862
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e25e5eb71ef'
down_revision: Union[str, Sequence[str], None] = '45914451cfe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_devices', sa.Column('expo_push_token', sa.String(length=200), nullable=True))
    op.add_column(
        'patient_profiles',
        sa.Column('timezone', sa.String(length=64), nullable=False, server_default='Asia/Kolkata'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'timezone')
    op.drop_column('patient_devices', 'expo_push_token')
    # ### end Alembic commands ###
