"""add routine items

Revision ID: 184198bc264d
Revises: e5045712b601
Create Date: 2026-09-09 18:07:48.399066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '184198bc264d'
down_revision: Union[str, Sequence[str], None] = 'e5045712b601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_items_patient_id'), 'routine_items', ['patient_id'], unique=False)
    op.create_table('routine_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_item_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marked_via', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['routine_item_id'], ['routine_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_item_id', 'on_date', name='uq_routine_completion')
    )
    op.create_index(op.f('ix_routine_completions_routine_item_id'), 'routine_completions', ['routine_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_completions_routine_item_id'), table_name='routine_completions')
    op.drop_table('routine_completions')
    op.drop_index(op.f('ix_routine_items_patient_id'), table_name='routine_items')
    op.drop_table('routine_items')
    # ### end Alembic commands ###
