"""add memory embedding column

Revision ID: b0e4f846e32e
Revises: 836a44165821
Create Date: 2026-09-09 14:08:12.607184
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'b0e4f846e32e'
down_revision: Union[str, Sequence[str], None] = '836a44165821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('memories', sa.Column('embedding_model', sa.Text(), nullable=True))
    op.execute(
        "CREATE INDEX ix_memories_embedding_hnsw ON memories "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_memories_embedding_hnsw")
    op.drop_column('memories', 'embedding_model')
    op.drop_column('memories', 'embedding')
    # ### end Alembic commands ###
