"""add memory_sources

Revision ID: 4119539e72a8
Revises: 7e25e5eb71ef
Create Date: 2026-09-09 20:06:11.560864
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4119539e72a8'
down_revision: Union[str, Sequence[str], None] = '7e25e5eb71ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Enum('dashboard_note', 'voice_transcript', 'chat', name='memory_origin', native_enum=False, length=20), nullable=False),
    sa.Column('raw_excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_sources_memory_id'), 'memory_sources', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_sources_memory_id'), table_name='memory_sources')
    op.drop_table('memory_sources')
    # ### end Alembic commands ###
