"""add memories

Revision ID: 836a44165821
Revises: 5d0868a0f5a6
Create Date: 2026-09-09 13:56:57.320162
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '836a44165821'
down_revision: Union[str, Sequence[str], None] = '5d0868a0f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('memory_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='memory_status', native_enum=False, length=12), nullable=False),
    sa.Column('source', sa.Enum('caregiver', 'ai_suggestion', name='memory_source', native_enum=False, length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_patient_id'), 'memories', ['patient_id'], unique=False)
    op.create_index(op.f('ix_memories_person_id'), 'memories', ['person_id'], unique=False)
    op.create_index(op.f('ix_memories_status'), 'memories', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_status'), table_name='memories')
    op.drop_index(op.f('ix_memories_person_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_patient_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
