"""add patient, caregiver, people, relationships

Revision ID: 97e23b951bed
Revises: 572b8a81f89c
Create Date: 2026-09-09 12:54:40.078371
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97e23b951bed'
down_revision: Union[str, Sequence[str], None] = '572b8a81f89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('home_label', sa.String(length=120), nullable=True),
    sa.Column('home_lat', sa.Float(), nullable=True),
    sa.Column('home_lng', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_caregivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('access_level', sa.Enum('owner', 'viewer', name='access_level', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'caregiver_id', name='uq_patient_caregiver')
    )
    op.create_index(op.f('ix_patient_caregivers_caregiver_id'), 'patient_caregivers', ['caregiver_id'], unique=False)
    op.create_index(op.f('ix_patient_caregivers_patient_id'), 'patient_caregivers', ['patient_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('relationship_label', sa.String(length=60), nullable=False),
    sa.Column('short_bio', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_patient_id'), 'people', ['patient_id'], unique=False)
    op.create_table('person_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('from_person_id', sa.Integer(), nullable=False),
    sa.Column('to_person_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.Enum('parent', 'child', 'spouse', 'sibling', 'grandparent', 'grandchild', 'friend', 'other', name='relationship_type', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_person_id', 'to_person_id', 'relationship', name='uq_person_relationship')
    )
    op.create_index(op.f('ix_person_relationships_from_person_id'), 'person_relationships', ['from_person_id'], unique=False)
    op.create_index(op.f('ix_person_relationships_patient_id'), 'person_relationships', ['patient_id'], unique=False)
    op.create_index(op.f('ix_person_relationships_to_person_id'), 'person_relationships', ['to_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_relationships_to_person_id'), table_name='person_relationships')
    op.drop_index(op.f('ix_person_relationships_patient_id'), table_name='person_relationships')
    op.drop_index(op.f('ix_person_relationships_from_person_id'), table_name='person_relationships')
    op.drop_table('person_relationships')
    op.drop_index(op.f('ix_people_patient_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_patient_caregivers_patient_id'), table_name='patient_caregivers')
    op.drop_index(op.f('ix_patient_caregivers_caregiver_id'), table_name='patient_caregivers')
    op.drop_table('patient_caregivers')
    op.drop_table('patient_profiles')
    op.drop_table('caregiver_profiles')
    # ### end Alembic commands ###
