"""add patient_devices

Revision ID: 7620e0e50f37
Revises: 97e23b951bed
Create Date: 2026-09-09 13:01:38.837277
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7620e0e50f37'
down_revision: Union[str, Sequence[str], None] = '97e23b951bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('pairing_code_hash', sa.String(length=64), nullable=True),
    sa.Column('pairing_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_jti', sa.String(length=64), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_devices_pairing_code_hash'), 'patient_devices', ['pairing_code_hash'], unique=False)
    op.create_index(op.f('ix_patient_devices_patient_id'), 'patient_devices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_devices_token_jti'), 'patient_devices', ['token_jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_devices_token_jti'), table_name='patient_devices')
    op.drop_index(op.f('ix_patient_devices_patient_id'), table_name='patient_devices')
    op.drop_index(op.f('ix_patient_devices_pairing_code_hash'), table_name='patient_devices')
    op.drop_table('patient_devices')
    # ### end Alembic commands ###
