"""add medications

Revision ID: e5045712b601
Revises: b0e4f846e32e
Create Date: 2026-09-09 17:31:28.557390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5045712b601'
down_revision: Union[str, Sequence[str], None] = 'b0e4f846e32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dosage_note', sa.String(length=200), nullable=True),
    sa.Column('schedule_times', sa.ARRAY(sa.String(length=5)), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('taken', 'skipped', 'missed', name='dose_status', native_enum=False, length=10), nullable=False),
    sa.Column('marked_via', sa.String(length=10), nullable=False),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_id', 'scheduled_date', 'scheduled_time', name='uq_dose_slot')
    )
    op.create_index(op.f('ix_medication_logs_medication_id'), 'medication_logs', ['medication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_logs_medication_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
